import * as nodemailer from "nodemailer";
import type { Transporter } from "nodemailer";

export interface SendInvoiceEmailOptions {
  to: string;
  invoiceNumber: string;
  poNumber: string;
  total: string;
  pdfBuffer: Buffer;
  customMessage?: string;
}

class EmailService {
  private transporter: Transporter;

  constructor() {
    // Uses environment SMTP if configured, otherwise falls back to a test account or jsonTransport
    const host = process.env.SMTP_HOST;
    if (host) {
      this.transporter = nodemailer.createTransport({
        host,
        port: Number(process.env.SMTP_PORT || 587),
        secure: process.env.SMTP_SECURE === "true",
        auth: {
          user: process.env.SMTP_USER,
          pass: process.env.SMTP_PASS,
        },
      });
    } else {
      // Clean JSON/stream transport for dev and test environments
      this.transporter = nodemailer.createTransport({
        jsonTransport: true,
      });
    }
  }

  async sendInvoice(options: SendInvoiceEmailOptions): Promise<{ success: boolean; messageId: string }> {
    const subject = `Invoice ${options.invoiceNumber} for Purchase Order ${options.poNumber} - VendorBridge ERP`;

    const html = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e5e7eb; border-radius: 8px;">
        <h2 style="color: #1E3A8A; margin-top: 0;">VendorBridge ERP</h2>
        <p>Dear Vendor,</p>
        <p>Please find attached the official procurement invoice <strong>${options.invoiceNumber}</strong> regarding Purchase Order <strong>${options.poNumber}</strong>.</p>
        <div style="background-color: #f3f4f6; padding: 15px; border-radius: 6px; margin: 20px 0;">
          <p style="margin: 5px 0;"><strong>Invoice Number:</strong> ${options.invoiceNumber}</p>
          <p style="margin: 5px 0;"><strong>Purchase Order:</strong> ${options.poNumber}</p>
          <p style="margin: 5px 0;"><strong>Total Amount:</strong> ₹${Number(options.total).toFixed(2)}</p>
        </div>
        ${options.customMessage ? `<p><strong>Additional Notes:</strong> ${options.customMessage}</p>` : ""}
        <p>The PDF document is attached with itemized breakdown, tax computation, and remittance details.</p>
        <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;" />
        <p style="color: #6b7280; font-size: 12px;">This is an automated procurement notification generated by VendorBridge ERP.</p>
      </div>
    `;

    const info = await this.transporter.sendMail({
      from: process.env.SMTP_FROM || '"VendorBridge Procurement" <procurement@vendorbridge.local>',
      to: options.to,
      subject,
      html,
      attachments: [
        {
          filename: `${options.invoiceNumber}.pdf`,
          content: options.pdfBuffer,
          contentType: "application/pdf",
        },
      ],
    });

    return {
      success: true,
      messageId: (info as any).messageId || "simulated-msg-id",
    };
  }
}

export const emailService = new EmailService();
